### ISSUE TITLE
Issue with multi_xml

### ISSUE THREAD

**Issue by kylesnowschwartz** [MagicTheGathering/mtg-sdk-ruby#1]
Howdy! This is an amazing project, so stoked to begin using this for my magic related side project right now.

One issue I found: upon installing the gem, I ran into this error 
`RuntimeError: missing dependency for FaradayMiddleware::ParseXml: cannot load such file -- multi_xml`

I noticed that my local version did not include `spec.add_dependency "multi_xml"` in the .gemspec file, so I just added it to my project's gemfile and it worked correctly.

Perhaps your last release omitted that dependency? Would appreciate if you released an update!

**Comment by adback03** [comment]
Thanks for pointing this out! It looks like I actually added the "multi_xml" to the gemspec last month, but never actually pushed out a new release that included the change! I'll be able to push out a new package later today. I'll close this issue once the new package is released. Let me know if you run into any other issues!

**Comment by adback03** [comment]
v1.1.1 has been released, which contains multi_xml as a dependency.
