### ISSUE TITLE
'Names' returns nil/doesn't exist

### ISSUE THREAD

**Issue by luketlancaster** [MagicTheGathering/mtg-sdk-ruby#3]
Playing around with the sdk, and working on a feature where I can return the images for double-faced cards. Was going to leverage the 'names' array the api returns, but the Cards object doesn't seem to have the appropriate information. For example, this:

https://api.magicthegathering.io/v1/cards?name=%22thing%20in%20the%20ice%22

Is the return that I'm expecting, instead I'm getting:

https://gist.github.com/luketlancaster/85d148a934e9fb2fd8193b6a55a75534

from `MTG::Card.where(name: "thing in the ice").all`

Am I missing something silly? Thanks for the time!

**Comment by adback03** [comment]
Nope, you are absolutely right in what you are expecting! It looks like I completely missed the "names" attribute in the [card_representer.rb](https://github.com/MagicTheGathering/mtg-sdk-ruby/blob/master/lib/mtg_sdk/representers/card_representer.rb). I will update the package later today with the appropriate fix.

Thanks for the heads up!

**Comment by luketlancaster** [comment]
👍 No problem! Thanks for the response!

**Comment by adback03** [comment]
Version 2.0.1 has been released, which has the fix for this bug.
